### ISSUE TITLE
Don’t go beyond the borders of the screen

### ISSUE THREAD

**Issue by Sebby37** [andymwat/TI-84-CE-DooM#1]
I went beyone the borders of the screen with the minimap and that basically reset my calculator with the ram cleared.

**Comment by andymwat** [comment]
> I went beyone the borders of the screen with the minimap and that basically reset my calculator with the ram cleared.
I can't reproduce this with the latest build in CEmu, but I added a check for that. I'll upload a fixed build pretty soon. In general, though, you won't be able to go beyond the borders of the minimap in any real map.

**Comment by andymwat** [comment]
Fixed in commit https://github.com/andymwat/TI-84-CE-DooM/commit/1c3da3f0cb177fbddee5da866c2761b8998004da.
